### GET PRODUCTS
GET http://localhost:3003/product
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4MDA4ZDFmLTUxNTEtNDBmMy05MjllLWU2NjQyMDBlMTMxZSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ5OTA3NDcsImV4cCI6MTY2NTA3NzE0N30.rhc25bUawoe64lmGW60RLrAk2QOBrntZiahM_ATGUf8"


### CREATE USER
POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name": "Gohan",
  "email": "gohangmail.com",
  "password": "123456"
}

### LOGIN
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "gohan@gmail.com",
  "password": "123456"
}

### ADD ORDER
POST http://localhost:3003/order/add-order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4MjM1NWI5LTBmYmQtNGRlNi04Zjc0LTYzNDFhZThiZWIwMCIsImlhdCI6MTY2NTUyODAwNSwiZXhwIjoxNjY1NjE0NDA1fQ.fWXhHQDN-KiZDborUfv19MdiRxVk-bfUPrMUKbvSrTA
Content-Type: application/json

{
  "productId": "16",
  "quantity": 1
}


### GET ORDER
GET http://localhost:3003/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4MjM1NWI5LTBmYmQtNGRlNi04Zjc0LTYzNDFhZThiZWIwMCIsImlhdCI6MTY2NTU5MjM5MCwiZXhwIjoxNjY1Njc4NzkwfQ.5NNmjXvksm8VLV_1QIGnattQVRwMiIaNvvxUmmlYuCs


### DELETE ORDER
PUT http://localhost:3003/order/delete-order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4MjM1NWI5LTBmYmQtNGRlNi04Zjc0LTYzNDFhZThiZWIwMCIsImlhdCI6MTY2NTU5MjM5MCwiZXhwIjoxNjY1Njc4NzkwfQ.5NNmjXvksm8VLV_1QIGnattQVRwMiIaNvvxUmmlYuCs
Content-Type: application/json

{
  "orderId": "45ec76d3-2aa8-41a9-9127-e4e2da652ecf"
}


### ADD DELIVERY DATE
POST http://localhost:3003/delivery/add-delivery
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4MjM1NWI5LTBmYmQtNGRlNi04Zjc0LTYzNDFhZThiZWIwMCIsImlhdCI6MTY2NTYyNjQyMiwiZXhwIjoxNjY1NzEyODIyfQ.SnWFUClh5Qsfc1QzHplsXSHNGEkCRJlD7wNDeS5aNec
Content-Type: application/json

{
   "receiveUserName": "Goku",
   "deliveryDate": "2022-11-22"
}


### GET DELIVERY DATE

GET http://localhost:3003/delivery
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4MjM1NWI5LTBmYmQtNGRlNi04Zjc0LTYzNDFhZThiZWIwMCIsImlhdCI6MTY2NTYyNjQyMiwiZXhwIjoxNjY1NzEyODIyfQ.SnWFUClh5Qsfc1QzHplsXSHNGEkCRJlD7wNDeS5aNec
