### GET PRODUCTS
GET http://localhost:3003/product
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4MDA4ZDFmLTUxNTEtNDBmMy05MjllLWU2NjQyMDBlMTMxZSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ5OTA3NDcsImV4cCI6MTY2NTA3NzE0N30.rhc25bUawoe64lmGW60RLrAk2QOBrntZiahM_ATGUf8"


### CREATE USER
POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name": "Vegeta",
  "email": "vegeta@gmail.com",
  "password": "123456",
  "role": "ADMIN"
}

### LOGIN
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "vegeta@gmail.com",
  "password": "123456"
}

### ADD ORDER
POST http://localhost:3003/order/add-order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiZGYxN2M4LWI3NTctNDM5MC05ODk4LWFlOTY0YmI0YTUwNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NTI2MCwiZXhwIjoxNjY1NDMxNjYwfQ.1jGxP2QFCCy0jBhuXDApp5vzjSHWL45asHIAvRLqutA
Content-Type: application/json

{
  "productId": "16",
  "quantity": 1
}


### GET ORDER
GET http://localhost:3003/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiZGYxN2M4LWI3NTctNDM5MC05ODk4LWFlOTY0YmI0YTUwNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NTI2MCwiZXhwIjoxNjY1NDMxNjYwfQ.1jGxP2QFCCy0jBhuXDApp5vzjSHWL45asHIAvRLqutA


### DELETE ORDER
PUT http://localhost:3003/order/delete-order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiZGYxN2M4LWI3NTctNDM5MC05ODk4LWFlOTY0YmI0YTUwNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NTI2MCwiZXhwIjoxNjY1NDMxNjYwfQ.1jGxP2QFCCy0jBhuXDApp5vzjSHWL45asHIAvRLqutA
Content-Type: application/json

{
  "orderId": "964906df-30d9-4835-9b95-e34645d33c93"
}


### ADD DELIVERY DATE
POST http://localhost:3003/delivery/add-delivery
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiZGYxN2M4LWI3NTctNDM5MC05ODk4LWFlOTY0YmI0YTUwNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NTI2MCwiZXhwIjoxNjY1NDMxNjYwfQ.1jGxP2QFCCy0jBhuXDApp5vzjSHWL45asHIAvRLqutA
Content-Type: application/json

{
   "receiveUserName": "Goku",
   "deliveryDate": "22/12/2022"
}


### GET DELIVERY DATE

GET http://localhost:3003/delivery
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiZGYxN2M4LWI3NTctNDM5MC05ODk4LWFlOTY0YmI0YTUwNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NTI2MCwiZXhwIjoxNjY1NDMxNjYwfQ.1jGxP2QFCCy0jBhuXDApp5vzjSHWL45asHIAvRLqutA
